fo = open("52_python.py", "a")
print("Enter the program to be appended: ")
read_user_str = input()
fo.write(read_user_str)
fo.close()
fo = open("52_python.py", "r")
read_file_str = fo.read()
print()
print(read_file_str)
fo.close()
